#!/bin/bash
#PATTERN=^[PTLSMWBC][AEIOUHRT][VLRNTSOI][DTHSIKVA][AEONLRCS][NDGRWTEY]$
#PATTERN=^[GHLMNRTD][RYAEIOUH][OMRAUFNS][AEIOUPGT][CGLNORST][TAEIOHNL][EDSTOLUC][NRKTYHES]$
PATTERN=${1:-^reg}
grep -i ${PATTERN} /usr/share/dict/words | tr A-Z a-z | sort -u
