#!/bin/bash
#
# Download the latest episode the Nextland podcast
#
RSS_URL=https://omny.fm/shows/the-nextlander-podcast/playlists/podcast.rss
RSS=$1

command -v wget >/dev/null 2>&1 || { echo >&2 "wget not available, aborting."; exit 1; }
command -v xmlstarlet >/dev/null 2>&1 || { echo >&2 "xmlstarlet not available, aborting."; exit 1; }

# Download RSS if none given.
if [ ! -f "${RSS}" ]; then
	TMPNAME=$(mktemp)
	RSS=${TMPNAME}
	echo "Downloading RSS."
	wget ${RSS_URL} -O "${RSS}"
fi

# Extract relevant data from XML
TITLE=$(xmlstarlet sel --text -t -v '/rss/channel/item[1]/title' ${RSS})
URL=$(xmlstarlet sel --text -t -v '/rss/channel/item[1]/enclosure/@url' ${RSS})
EPISODE=$(xmlstarlet sel --text -t -v '/rss/channel/item[1]/itunes:episode' ${RSS})
PUBDATE=$(xmlstarlet sel --text -t -v '/rss/channel/item[1]/pubDate' ${RSS})
DATE=$(date +"%Y-%m-%d" --date="${PUBDATE}")

# Download if necessary.
if [ ! -z ${URL} ]; then
	DEST="Nextlander - ${EPISODE} - ${TITLE%\?} (${DATE}).mp3"
	if [ ! -f "${DEST}" ]; then
		echo "Downloading podcast episode."
		wget ${URL} -O "${DEST}"
	else
		echo "Episode '$TITLE' already downloaded."
	fi
fi

if [ ! -z "${TMPNAME}" ]; then
	rm ${TMPNAME}
fi
